# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "rr-bp13k3q7292ce5t6k9o.mysql.rds.aliyuncs.com:3306"
my_user = "sjfxadmin"
my_pass = "f7na4ZQmCcXhx5gGKsr3"
my_charset = "utf8"

# Set true when elasticsearch use https
#es_https = false
# Elasticsearch address
es_addr = "192.168.1.12:9200"
# Elasticsearch user and password, maybe set by shield, nginx, or x-pack
es_user = "elastic"
es_pass = "E7rHbFbWXxLWY9Bj"

# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing. 
# TODO: support other storage, like etcd. 
data_dir = "/goelkvar"

# Inner Http status address
stat_addr = "192.168.1.12:12800"
stat_path = "/metrics"

# pseudo server id like a slave 
server_id = 2204155072

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

# Ignore table without primary key
skip_no_pk_table = false

# MySQL data source
[[source]]
schema = "user_service"

# Only below tables will be synced into Elasticsearch.
# "t_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
tables = ["user","erp_member","user_employee","customer_user"]

#[[rule]]
#schema = "user_service"
#table = "user"
#index = "user"
#type = "user"
#id = ["id"]
