version: '2'

services:

  # elasticsearch:
  #   build:
  #     context: elasticsearch/
  #   volumes:
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  #     - /mnt/elasticsearchdata:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx2g -Xms2g"
  #     ELASTIC_PASSWORD: E7rHbFbWXxLWY9Bj
  #   networks:
  #     - elk

  logstashback:
    build:
      context: logstash/
    volumes:
      - ./logstash/backconfig/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/backpipeline:/usr/share/logstash/pipeline:ro
      - /etc/localtime:/etc/localtime
      - /mnt/logstashbackdata:/usr/share/logstash/data
      - /mnt/logstashbacklog:/usr/share/logstash/log
      - /sjfxlogs/:/sjfxlogs/
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    # networks:
    #   - elk
    # depends_on:
    #   - elasticsearch
  
  # logstashdocker:
  #   build:
  #     context: logstash/
  #   volumes:
  #     - ./logstash/dockerconfig/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/dockerpipeline:/usr/share/logstash/pipeline:ro
        # - /etc/localtime:/etc/localtime
  #     - /mnt/logstashdockerdata:/usr/share/logstash/data
  #     - /mnt/logstashdockerlog:/usr/share/logstash/log
  #   ports:
  #     - "30002:30002"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx1g -Xms1g"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  logstashgateway:
    build:
      context: logstash/
    volumes:
      - ./logstash/gatewayconfig/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/gatewaypipeline:/usr/share/logstash/pipeline:ro
      - /etc/localtime:/etc/localtime
      - /mnt/logstashgatewaydata:/usr/share/logstash/data
      - /mnt/logstashgatewaylog:/usr/share/logstash/log
      - /sjfxlogs/:/sjfxlogs/
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

#   kibana:
#     build:
#       context: kibana/
#     volumes:
#       - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        # - /etc/localtime:/etc/localtime
#     ports:
#       - "5601:5601"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

# networks:

#   elk:
#     driver: bridge
