sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/demo-app.git base-demo-app
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/id-generator.git base-id-generator
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/eureka-server.git base-eureka-server
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/spring-boot-admin.git base-spring-boot-admin
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/config-service.git base-config-service
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/publish-script.git base-publish-script
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/BASE/zipkin.git base-zipkin
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/wx-gateway.git market-wx-gateway
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/db.git market-db
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/authorization.git market-authorization
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/commonlib.git market-commonlib
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/erp-sync.git market-erp-sync
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/tenant.git market-tenant
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/gateway.git market-gateway
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/coupon.git market-coupon
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/user-service.git market-user-service
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/giftmall.git market-giftmall
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/sms.git market-sms
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/oss.git market-oss
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/warranty.git market-warranty
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/product.git market-product
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/erp_to_platform.git market-erp_to_platform
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/h5link.git market-h5link
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/comment.git market-comment
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/valueadded.git market-valueadded
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/position.git market-position
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/message_push.git market-message_push
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/account.git market-account
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/activity.git market-activity
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/tag.git market-tag
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/custom-page.git market-custom-page
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/qrcode.git market-qrcode
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/employee.git market-employee
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/MAR/customer.git market-customer
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/VUE/Portal.git vue-Portal
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/VUE/Mobile.git vue-Mobile
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/VUE/sjfx.git vue-sjfx
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/CONFIG/market-dev-configs.git config-market-dev-configs
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/CONFIG/market-configs.git config-market-configs
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/DEMO/demo.git demo-demo
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/CUSTOM/lubin-product-source.git customization-lubin-product-source
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/CUSTOM/lubin-product-source-web.git customization-lubin-product-source-web
