sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/demo-app.git base-demo-app
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/id-generator.git base-id-generator
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/eureka-server.git base-eureka-server
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/spring-boot-admin.git base-spring-boot-admin
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/config-service.git base-config-service
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/publish-script.git base-publish-script
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/zipkin.git base-zipkin
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/base/sql-script.git base-sql-script
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/wx-gateway.git market-wx-gateway
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/db.git market-db
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/authorization.git market-authorization
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/commonlib.git market-commonlib
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/erp-sync.git market-erp-sync
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/tenant.git market-tenant
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/gateway.git market-gateway
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/coupon.git market-coupon
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/user-service.git market-user-service
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/giftmall.git market-giftmall
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/sms.git market-sms
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/oss.git market-oss
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/warranty.git market-warranty
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/product.git market-product
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/erp_to_platform.git market-erp_to_platform
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/h5link.git market-h5link
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/comment.git market-comment
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/valueadded.git market-valueadded
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/position.git market-position
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/message_push.git market-message_push
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/account.git market-account
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/activity.git market-activity
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/tag.git market-tag
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/custom-page.git market-custom-page
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/qrcode.git market-qrcode
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/employee.git market-employee
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/customer.git market-customer
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/sql-script.git market-sql-script
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/statistics.git market-statistics
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/deliver.git market-deliver
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/facepass-sync.git market-facepass-sync
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/goods.git market-goods
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/payment.git market-payment
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/order.git market-order
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/market/booking.git market-booking
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/vue/Portal.git vue-Portal
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/vue/Mobile.git vue-Mobile
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/vue/sjfx.git vue-sjfx
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/vue/web-statistics.git vue-web-statistics
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/config/market-dev-configs.git config-market-dev-configs
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/config/market-configs.git config-market-configs
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/demo/demo.git demo-demo
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/customization/lubin-product-source.git customization-lubin-product-source
sh /opt/backupcode.sh ssh://git@bit.sjfx.com.cn:7999/customization/lubin-product-source-web.git customization-lubin-product-source-web
