version: '2'
services:
  namesrv:
    build:
      context: ./namesrv
    image:  sjfx/rocketmq-namesrv:4.2.0
    ports:
      - 9876:9876
    volumes:
      - ./namesrv/logs:/opt/logs
      - ./namesrv/store:/opt/store
    container_name: rmqnamesrv
  broker:
    build:
      context: ./broker
      args: 
        runip: "192.168.1.11"
    image:  sjfx/rocketmq-broker:4.2.0
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./broker/logs:/opt/logs
      - ./broker/store:/opt/store
    container_name: rmqbroker
    depends_on:
      - namesrv
