---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-x-pack.yml
#
path.config: /usr/share/logstash/pipeline
path.data:   /usr/share/logstash/data
path.logs:   /usr/share/logstash/log
xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: E7rHbFbWXxLWY9Bj
# unset by default. see:
# https://www.elastic.co/guide/en/logstash/current/ls-security.html#ls-monitoring-user
