version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: E7rHbFbWXxLWY9Bj
    restart: unless-stopped
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstashdata:/usr/share/logstash/data
      - ./logstashlog:/usr/share/logstash/log
    ports:
      - "30000-30030:30000-30030"
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    restart: unless-stopped
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    restart: unless-stopped
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
