version: '2'

services:
 mail:
 image: tvial/docker-mailserver
 hostname: mail
 domainname: sjfx.com.cn
 container_name: mail
 ports:
 - "25:25"
 - "143:143"
 - "587:587"
 - "993:993"
 volumes:
 - /mnt/mail/mail:/var/mail
 - /mnt/mail/mail-state:/var/mail-state
 - /mnt/mail/config/:/tmp/docker-mailserver/
 - /mnt/mail/letsencrypt:/etc/letsencrypt
 environment:
 - ENABLE_SPAMASSASSIN=0
 - ENABLE_CLAMAV=0
 - ENABLE_FAIL2BAN=1
 - ONE_DIR=1
 - DMS_DEBUG=0
 - SSL_TYPE=letsencrypt
 cap_add:
 - NET_ADMIN